name: SpotBugs 

on: workflow_dispatch

jobs:
    spotbugs:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
        # set up java
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            java-version: '8'
            distribution: 'temurin'

        # build project with maven
        - name: Build with maven
          run: mvn clean package
        
        # run SpotBugs
        - name: Run SpotBugs
          run: mvn spotbugs:check
        